orchestracities/anubis

.github/workflows/policy-api-tests.yml, README.md, RELEASE_NOTES.md, anubis-management-api/src/main.py, docker-compose.yaml, scripts/test_cors.sh
Added a way to configure CORS settings for the Policy API, useful for frontend implementation
feature works
"Martel Open Source …
=> Cors settings for API

RELEASE_NOTES.md, anubis-management-api/src/policies/routers.py, anubis-management-api/src/tests/test_policies.py, scripts/test_policy_api.sh
Ensures that if a policy already exists for a given resource, the API will prevent the creation of one that provides the same level of access.
feature works
[cla]: …
=> 59 - Checking against policy duplication

RELEASE_NOTES.md, anubis-management-api/src/main.py, anubis-management-api/src/tests/test_api.py, anubis-management-api/src/version.py
Implement `/version` endpoint #71
feature works
[contrib]: …
=> add version end point

RELEASE_NOTES.md, docs/admin/customize.md, docs/user/policies.md, mkdocs.yml
fix formatting of code blocks
feature works
N/A
[release]: https://github.com/orchestracities/anubis/blob/master/RELEASE_N …
=> fix formatting

RELEASE_NOTES.md, anubis-management-api/src/default.py, anubis-management-api/src/policies/operations.py, anubis-management-api/src/policies/routers.py, anubis-management-api/src/tests/test_policies.py, docs/user/walkthrough.md, open-api-spec/openapi.json
Added the option to filter policies by agent type (e.g. acl:agent, acl:agentRole, acl:agentGroup)
feature works
"Martel Open Source …
=> Agent type filter for policies endpoint

.readthedocs.yml, README.md, RELEASE_NOTES.md, docs/requirements.txt, mkdocs.yml
- Update Readme, add hitbox
- Update CSS to security variant
- Pin MKDocs libraries.
- [ x] Bugfix (non-breaking change which fixes an issue)
feature works
[contrib]: https://github.com/orchestracities/anubis/blob/master/CONTRIB …
=> Documentation fixes

.github/workflows/policy-api-tests.yml, RELEASE_NOTES.md, anubis-management-api/src/database.py, anubis-management-api/src/policies/models.py, docker-compose.yaml, scripts/clean.sh
Test both sqlite and postgresql backends
feature works …
=> support testing both db backends

Dockerfile, RELEASE_NOTES.md, anubis-management-api/logging.yaml, anubis-management-api/src/database.py
1. SQLAlchemy logs are too verbose -> disable them
2. Enable access logs for uvicorn
feature works
N/A
[release]: …
=> Fix api logging

README.md, RELEASE_NOTES.md, anubis-management-api/src/version.py, docs/user/walkthrough.md, open-api-spec/openapi.json
Set-up repository for 0.2.0 release
feature works
N/A
[release]: …
=> Set-up repository for 0.2.0 release

RELEASE_NOTES.md, anubis-management-api/src/version.py, docs/quick_start_guide.md, docs/user/walkthrough.md, open-api-spec/openapi.json
Set-up 0.3.0-dev cycle
feature works
N/A …
=> 0.3.0-dev set-up

RELEASE_NOTES.md, anubis-management-api/Pipfile, anubis-management-api/Pipfile.lock, anubis-management-api/src/policies/operations.py, anubis-management-api/src/policies/routers.py, anubis-management-api/src/rego.py, anubis-management-api/src/tests/test_policies.py, config/envoy/v3.yaml, config/opa-service/rego/anubis_management_api_policy.rego, config/opa-service/rego/anubis_management_api_policy_test.rego, config/opa-service/rego/common.rego, config/opa-service/rego/context_broker_policy_test.rego, docs/user/walkthrough.md, open-api-spec/openapi.json
Revised the mappings for acl to HTTP methods, and the behaviour of `acl:Control`
feature works
"Martel Open Source Software …
=> Revised mappings, acl:Control behaviour

RELEASE_NOTES.md, anubis-management-api/anubis/version.py, anubis-management-api/setup.py, docs/user/walkthrough.md, open-api-spec/openapi.json
Prepare repository for 0.3.0 release
feature works
N/A
[release]: …
=> release 0.3.0

RELEASE_NOTES.md, anubis-management-api/anubis/version.py, docs/user/walkthrough.md, open-api-spec/openapi.json
Prepare 0.4.0-dev
feature works
N/A …
=> Prepare 0.4.0 dev

RELEASE_NOTES.md, anubis-management-api/anubis/version.py, docs/user/walkthrough.md, open-api-spec/openapi.json
Prepare release 0.4.0
feature works
N/A …
=> prepare release 0.4.0

.github/workflows/build-and-push-python-package.yml, .github/workflows/todo.yml, RELEASE_NOTES.md
Track TODOs inserted in the code and open issues.
feature works
N/A
[release]: …
=> track todos in the code and open issues

RELEASE_NOTES.md, anubis-management-api/anubis/tenants/routers.py, docs/user/walkthrough.md, open-api-spec/openapi.json
Describe the big picture of your changes here to communicate to the
maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to
that issue.
feature works
N/A …
=> Delete tenant in keycloak

.gitignore, README.md, RELEASE_NOTES.md, docker-compose.yaml, scripts/test_load.sh
This pr introduces a script to run load tests and measure the overhead introduced by Anubis.
feature works
N/A
[release]: …
=> load testing

RELEASE_NOTES.md, anubis-management-api/anubis/version.py, docs/user/walkthrough.md, open-api-spec/openapi.json
Describe the big picture of your changes here to communicate to the
maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to
that issue.
- [] Bugfix (non-breaking change which fixes an issue)
feature works
N/A
"Martel Open Source …
=> prepare release 0.5.0

RELEASE_NOTES.md, anubis-management-api/anubis/version.py, docs/user/walkthrough.md, open-api-spec/openapi.json
Prepare 0.6.0-dev
feature works
N/A …
=> prepare 0.6.0-dev

RELEASE_NOTES.md, anubis-management-api/anubis/audit/models.py, anubis-management-api/anubis/policies/models.py, anubis-management-api/anubis/tenants/models.py
Add drop all to database models
feature works
N/A
[release]: https://github.com/orchestracities/anubis/blob/master/RELEASE …
=> Add drop all

.env, RELEASE_NOTES.md, docker-compose.yaml
Fix demo script configuration to UI 0.6 changes
feature works
N/A
[release]: …
=> Fix demo script configuration to UI 0.6 changes

README.md, RELEASE_NOTES.md, anubis-management-api/anubis/policies/operations.py, anubis-management-api/anubis/policies/routers.py, anubis-management-api/anubis/tenants/routers.py, config/opa-service/rego/anubis_management_api_policy.rego, config/opa-service/rego/common.rego, config/opa-service/rego/nop.rego, docker-compose.yaml, docs/admin/install.md, scripts/init_opa.sh, scripts/test_context_broker.sh, scripts/test_load.sh
Instead of pulling all policies from OPA on every call being processed, we instead push the policies from the Policy API when a policy is created/edited/deleted
feature works
[cla]: …
=> 14 - Moving from pulling policies from rego to pushing them from Anubis Policy API

RELEASE_NOTES.md, config/opa-service/lua/common.lua
Checking for post requests to avoid issue with retrieving data
Fixes #186
Fixes #185 
feature works
"Martel Open Source Software …
=> Fix for potential issue with context broker policies

RELEASE_NOTES.md, anubis-management-api/anubis/middleware/routers.py, anubis-management-api/anubis/policies/operations.py, anubis-management-api/anubis/policies/routers.py, anubis-management-api/anubis/tenants/routers.py, open-api-spec/api-manager/openapi.json
Added total counter when querying policies and set 1000 as default limit for queries. This should facilitate UI pagination and tracking policy numbers.
Relates to issues #191 and #197 
feature works
[cla]: …
=> Added total counter when querying policies, set 1000 as default limit for queries

RELEASE_NOTES.md, anubis-management-api/anubis/policies/operations.py, anubis-management-api/anubis/policies/routers.py, anubis-management-api/anubis/tests/test_policies.py, anubis-management-api/anubis/tests/test_rdf_parsing.py, anubis-management-api/anubis/wac.py, config/opa-service/rego/anubis_management_api_policy.rego, scripts/test_policy_api.sh
- When calling /v1/policies/me it will show foaf:Agent type policies when no token passed. If token indicates admin or super admin, will show all of them ( fixes #148 and fixes #149  )
- Fixed issue with rdf conversion of agents ( fixes #146 )
feature works
"Martel Open Source Software Individual …
=> Public policies filtering with tokens, rdf conversion fixes

RELEASE_NOTES.md, docs/quick_start_guide.md
Fixes #225
feature works
"Anubis …
=> Fix to the quickstart
